import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../dist/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home / X",
  description: "Generated by create next app",
  icons: {
    icon: "/images/title/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
